# Generated by Django 5.1.7 on 2025-03-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='details_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='ranking',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
