# Generated by Django 5.1.7 on 2025-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_university_details_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(upload_to='media/universities/'),
        ),
    ]
