# Generated by Django 5.1.7 on 2025-03-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_country_alter_university_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
