# Generated by Django 5.1.7 on 2025-03-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_country_alter_university_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychoose',
            name='title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
